apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-application
    newTag: RELEASE_TAG
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-chat
    newTag: RELEASE_TAG
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-frontend
    newTag: RELEASE_TAG
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-game-engine
    newTag: RELEASE_TAG
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-genai
    newTag: RELEASE_TAG
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-postgres
    newTag: RELEASE_TAG
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-postgres-exporter
    newTag: RELEASE_TAG
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-chat-db-exporter
    newTag: RELEASE_TAG
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-prometheus
    newTag: RELEASE_TAG
  - name: ghcr.io/aet-devops26/team-merge-build-repeat-grafana
    newTag: RELEASE_TAG
