apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/databases/application-database.yaml
  - base/databases/chat-database.yaml
  - base/apps/application.yaml
  - base/apps/chat.yaml
  - base/apps/genai.yaml
  - base/apps/game-engine.yaml
  - base/apps/frontend.yaml
  - base/networking/services.yaml
  - base/networking/ingress.yaml
