---
app_database_name: "{{ lookup('env', 'APP_DATABASE_NAME') | default('game_database', true) }}"
app_database_user: "{{ lookup('env', 'APP_DATABASE_USER') | default('app_user', true) }}"
chat_database_name: "{{ lookup('env', 'CHAT_DATABASE_NAME') | default('chat_database', true) }}"
chat_database_user: "{{ lookup('env', 'CHAT_DATABASE_USER') | default('chat_user', true) }}"
chat_database_spring_profile: "{{ lookup('env', 'CHAT_DATABASE_SPRING_PROFILE') | default('docker', true) }}"

app_domain: "{{ lookup('env', 'DOMAIN') }}"
app_image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
app_database_password: "{{ lookup('env', 'APP_DATABASE_PASSWORD') }}"
chat_database_password: "{{ lookup('env', 'CHAT_DATABASE_PASSWORD') }}"
