---
app_database_name: "{{ lookup('env', 'APP_DATABASE_NAME') | default('game_database', true) }}"
app_database_user: "{{ lookup('env', 'APP_DATABASE_USER') | default('app_user', true) }}"
chat_database_name: "{{ lookup('env', 'CHAT_DATABASE_NAME') | default('chat_database', true) }}"
chat_database_user: "{{ lookup('env', 'CHAT_DATABASE_USER') | default('chat_user', true) }}"
chat_database_spring_profile: "{{ lookup('env', 'CHAT_DATABASE_SPRING_PROFILE') | default('docker', true) }}"
application_context_path: "{{ lookup('env', 'APPLICATION_CONTEXT_PATH') | default('/application', true) }}"
chat_context_path: "{{ lookup('env', 'CHAT_CONTEXT_PATH') | default('/chat', true) }}"
genai_root_path: "{{ lookup('env', 'GENAI_ROOT_PATH') | default('/genai', true) }}"
game_engine_root_path: "{{ lookup('env', 'GAME_ENGINE_ROOT_PATH') | default('/game-engine', true) }}"
supabase_auth_issuer: "{{ lookup('env', 'SUPABASE_AUTH_ISSUER') | default('https://pwjnldzqwwagnxjycfaq.supabase.co/auth/v1', true) }}"
supabase_auth_jwks_uri: "{{ lookup('env', 'SUPABASE_AUTH_JWKS_URI') | default('https://pwjnldzqwwagnxjycfaq.supabase.co/auth/v1/.well-known/jwks.json', true) }}"

app_domain: "{{ lookup('env', 'DOMAIN') }}"
app_image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
app_database_password: "{{ lookup('env', 'APP_DATABASE_PASSWORD') }}"
chat_database_password: "{{ lookup('env', 'CHAT_DATABASE_PASSWORD') }}"
logos_key: "{{ lookup('env', 'LOGOS_KEY') }}"
