spring:
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configtree:/run/secrets/}
  application:
    name: merge-build-repeat
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:application-database}:${DATABASE_PORT:5432}/${DATABASE_NAME:game_database}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:alnvicawlae}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  info:
    build:
      enabled: true
