apiVersion: 1

groups:

  - orgId: 1
    name: "app-alerts"
    folder: "Infrastructure"
    interval: 1m
    rules:
      - uid: "low-request-count"
        title: "Low Request Count"
        condition: B
        for: 5m
        noDataState: "NoData"
        execErrState: "Error"
        annotations:
          summary: "Request count is low for one or more jobs"
          description: "sum by(job) (increase(http_server_requests_seconds_count[5m])) is below threshold."
        labels:
          severity: "warning"
        data:
          - refId: "A"
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: "prometheus-ds"
            model:
              refId: "A"
              expr: "sum by(job) (increase(http_server_requests_seconds_count[5m]))"
              instant: true
          - refId: "B"
            datasourceUid: "__expr__"
            model:
              refId: "B"
              type: "threshold"
              expression: "A"
              conditions:
                - type: "query"
                  reducer:
                    type: "last"
                  operator:
                    type: "and"
                  evaluator:
                    type: "lt"
                    params: [ 1 ]

      - uid: high-latency-http-server
        title: High Latency - http_server_requests_seconds
        condition: B
        for: 5m
        noDataState: NoData
        execErrState: Error
        annotations:
          summary: High latency detected
          description: Mean latency from http_server_requests_seconds is above 500ms.
        labels:
          severity: warning
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus-ds
            model:
              refId: A
              expr: 1000 * sum by (job) (rate(http_server_requests_seconds_sum[5m])) / clamp_min(sum by (job) (rate(http_server_requests_seconds_count[5m])), 0.000000001)
              instant: true
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: threshold
              expression: A
              conditions:
                - type: query
                  reducer:
                    type: last
                  operator:
                    type: and
                  evaluator:
                    type: gt
                    params: [500]

      - uid: high-latency-http-requests
        title: High Latency - http_request_duration_seconds
        condition: B
        for: 5m
        noDataState: NoData
        execErrState: Error
        annotations:
          summary: High latency detected
          description: Mean latency from http_request_duration_seconds is above 500ms.
        labels:
          severity: warning
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus-ds
            model:
              refId: A
              expr: 1000 * sum by (job) (rate(http_request_duration_seconds_sum[5m])) / clamp_min(sum by (job) (rate(http_request_duration_seconds_count[5m])), 0.000000001)
              instant: true
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: threshold
              expression: A
              conditions:
                - type: query
                  reducer:
                    type: last
                  operator:
                    type: and
                  evaluator:
                    type: gt
                    params: [500]


      - uid: high-db-rollback-rate
        title: High DB Rollback Rate
        condition: B
        for: 10m
        noDataState: NoData
        execErrState: Error
        annotations:
          summary: Database rollback ratio is high
          description: Rollback ratio is above 2%.
        labels:
          severity: warning
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus-ds
            model:
              refId: A
              expr: 100 * sum by (job) (rate(pg_stat_database_xact_rollback[5m])) / clamp_min((sum by (job) (rate(pg_stat_database_xact_commit[5m])) + sum by (job) (rate(pg_stat_database_xact_rollback[5m]))), 0.000000001)
              instant: true
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: threshold
              expression: A
              conditions:
                - type: query
                  reducer:
                    type: last
                  operator:
                    type: and
                  evaluator:
                    type: gt
                    params: [2]

      - uid: spring_boot_down_alert
        title: Spring Boot Application is DOWN
        condition: B
        for: 1m
        noDataState: NoData
        execErrState: Alerting
        annotations:
          summary: "App is down"
          description: "The Spring Boot application {{ $labels.job }} has been offline for more than 1 minute."
        labels:
          severity: critical
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus-ds
            model:
              refId: A
              expr: up{job="application-service"}
              instant: true
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: threshold
              expression: A
              conditions:
                - type: query
                  reducer:
                    type: last
                  operator:
                    type: and
                  evaluator:
                    type: lt
                    params: [1]


      - uid: app_postgres_down
        title: App PostgreSQL Down
        condition: B
        for: 1m
        noDataState: NoData
        execErrState: Alerting
        annotations:
          summary: "App database is down"
          description: "Target app-db-exporter:9187 (job=app-databases) is down for more than 1 minute."
        labels:
          severity: critical
          service: app-database
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus-ds
            model:
              refId: A
              expr: pg_up{job="app-databases",instance="app-db-exporter:9187"}
              instant: true
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: threshold
              expression: A
              conditions:
                - type: query
                  reducer:
                    type: last
                  operator:
                    type: and
                  evaluator:
                    type: lt
                    params: [ 1 ]

      - uid: chat_postgres_down
        title: Chat PostgreSQL Down
        condition: B
        for: 1m
        noDataState: NoData
        execErrState: Alerting
        annotations:
          summary: "Chat database is down"
          description: "Target chat-db-exporter:9187 (job=chat-databases) is down for more than 1 minute."
        labels:
          severity: critical
          service: chat-database
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus-ds
            model:
              refId: A
              expr: pg_up{job="chat-databases",instance="chat-db-exporter:9187"}
              instant: true
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: threshold
              expression: A
              conditions:
                - type: query
                  reducer:
                    type: last
                  operator:
                    type: and
                  evaluator:
                    type: lt
                    params: [ 1 ]

      - uid: chat_service_down_alert
        title: Chat Service Application is DOWN
        condition: B
        for: 1m
        noDataState: NoData
        execErrState: Alerting
        annotations:
          summary: "Instance chat:8080 is down"
          description: "The Chat Service application chat-service has been offline for more than 1 minute."
        labels:
          severity: critical
          service: chat-service
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus-ds
            model:
              refId: A
              expr: up{job="chat-service",instance="chat:8080"}
              instant: true
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: threshold
              expression: A
              conditions:
                - type: query
                  reducer:
                    type: last
                  operator:
                    type: and
                  evaluator:
                    type: lt
                    params: [ 1 ]

      - uid: game_engine_service_down_alert
        title: Game Engine Service Application is DOWN
        condition: B
        for: 1m
        noDataState: NoData
        execErrState: Alerting
        annotations:
          summary: "Instance game-engine:8080 is down"
          description: "The Game Engine Service application game-engine-service has been offline for more than 1 minute."
        labels:
          severity: critical
          service: game-engine-service
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus-ds
            model:
              refId: A
              expr: up{job="game-engine-service",instance="game-engine:8080"}
              instant: true
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: threshold
              expression: A
              conditions:
                - type: query
                  reducer:
                    type: last
                  operator:
                    type: and
                  evaluator:
                    type: lt
                    params: [ 1 ]

      - uid: genai_service_down_alert
        title: GenAI Service Application is DOWN
        condition: B
        for: 1m
        noDataState: NoData
        execErrState: Alerting
        annotations:
          summary: "Instance genai:8080 is down"
          description: "The GenAI Service application genai-service has been offline for more than 1 minute."
        labels:
          severity: critical
          service: genai-service
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus-ds
            model:
              refId: A
              expr: up{job="genai-service",instance="genai:8080"}
              instant: true
          - refId: B
            datasourceUid: __expr__
            model:
              refId: B
              type: threshold
              expression: A
              conditions:
                - type: query
                  reducer:
                    type: last
                  operator:
                    type: and
                  evaluator:
                    type: lt
                    params: [ 1 ]

