server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/game-engine/ {
    proxy_pass http://game-engine:8080/;
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /health {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "OK\n";
  }
}
