apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - databases/application-database.yaml
  - databases/chat-database.yaml
  - apps/application.yaml
  - apps/chat.yaml
  - apps/genai.yaml
  - apps/game-engine.yaml
  - apps/frontend.yaml
  - apps/monitoring.yaml
  - networking/services.yaml
  - networking/ingress.yaml
