version = 1

[secrets.app_database_password]
type = "generated"
bytes = 64
file = "app_database_password"

[secrets.chat_database_password]
type = "generated"
bytes = 64
file = "chat_database_password"

[secrets.logos-key]
type = "manual"
file = "logos-key"
